#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'countingSort' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY arr as parameter.
#

def countingSort(arr):
    # Write your code here
    max_num=-1
    for i in range(0,(len(arr))):
        
        if(max_num<arr[i]):
            max_num=arr[i]
        
        
    final=[0 for x in range (100)]
    print(len(final))
    #for nums in final:
        #nums=0
        
    for i in range(0,(len(arr)),1):
        num=arr[i]
        final[num]=final[num]+1
    
    return final
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    result = countingSort(arr)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
